### ISSUE TITLE
Departure events not registering, causing app lockup

### ISSUE THREAD

**Issue by pycal** [gimbalinc/hello-gimbal-ios-swift#2]
Hey, departure events never register because of an error trying to access an invalid property. I've submitted a pull request:

https://github.com/gimbalinc/hello-gimbal-ios-swift/pull/1

**Comment by garydamm** [comment]
Thank you for finding this issue. I've updated the app with your pull request change. Visit End now prints the departureDate to the screen.

Sorry for the delay in responding.
