### ISSUE TITLE
didBeginVisit not calling

### ISSUE THREAD

**Issue by srinathp90** [gimbalinc/hello-gimbal-ios-swift#3]
If the app already inside the Gimbal place then didBeginVisit:(GMBLPlaceManagerDelegate) will not be called.

**Comment by garydamm** [comment]
Hello, I tested the scenario where I was both inside a geofence and proximate to a beacon when the application was installed and once it started I did receive arrivals for both.

If you continue to see this issue please reopen this ticket with more details about the device and iOS version you are using.

Thanks.
