### ISSUE TITLE
GMBLPlaceManagerDelegate not working when quits the app

### ISSUE THREAD

**Issue by srinathp90** [gimbalinc/hello-gimbal-ios-swift#4]
GMBLPlaceManagerDelegate Begin/End visit will not be called when quits the App

**Comment by garydamm** [comment]
Can you please provide the device and iOS version you are using when you experience this issue.

**Comment by srinathp90** [comment]
I tested in iPhone 6 Plus (iOS version 9.3.5) and iPhone 6 (iOS version 10.1.1). Xcode version 8. I have added **Uses Bluetooth LE accessories** bluetooth-central in info.plist.

**Comment by garydamm** [comment]
Let me make sure I understand. You have a Gimbal Beacon configured as a Place. In your application you are getting Place Events for this beacon. But, when you kill the app you no longer get Place Events. Is that accurate?

If so, how long are you waiting to see if you arrive at the beacon once you kill the application? In testing we sometimes find it takes up to 2 minutes to arrive when the application was force killed by the user. Not always, the behavior is somewhat inconsistent but also somewhat of a black box from the OS.
